resources:
- ../../base

namePrefix: dev-

patches:
- path: replicas.yaml

configMapGenerator:
- name: example-app-config
  envs:
  - application.properties

patches:
  - target:
      kind: Ingress
      name: example-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: local.example.com