resources:
- ../../base
# By importing a file here, a specific resource can be created only in this customization
- ./clusterip.yaml

namePrefix: prod-

patches:
- path: replicas.yaml

configMapGenerator:
- name: example-app-config
  envs:
  - application.properties